In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Loaded")

Libraries Loaded

In [3]:
train_df = pd.read_csv(
    "../data/processed/train_engineered.csv"
)

print("Shape:", train_df.shape)

train_df.head()

Shape: (61249, 54)

,unit_number,time_cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,max_cycle,RUL,engine_age,life_fraction,operating_cluster,sensor_1_norm,sensor_2_norm,sensor_3_norm,sensor_4_norm,sensor_5_norm,sensor_6_norm,sensor_7_norm,sensor_8_norm,sensor_9_norm,sensor_11_norm,sensor_12_norm,sensor_13_norm,sensor_14_norm,sensor_17_norm,sensor_18_norm,sensor_19_norm,sensor_20_norm,sensor_21_norm,sensor_11_rolling_mean,sensor_14_rolling_mean,sensor_4_rolling_mean,sensor_17_rolling_mean,sensor_11_delta,sensor_14_delta,sensor_4_delta,sensor_17_delta
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,41.69,129.78,2387.99,8074.83,330,2212,100.00,10.62,6.3670,321,320,1,0.003115,0,0.000000,0.435212,-1.384507,-1.281784,0.999968,-0.750182,-1.514018,-0.607831,-0.876629,-1.207006,-1.092748,-0.385986,-0.945350,-0.327361,0.0,0.0,-0.024002,-0.079912,41.6900,8074.830000,1112.930000,330.0,0.00,0.00,0.00,0.0
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,2323.66,8713.60,43.94,312.59,2387.73,8046.13,361,2324,100.00,24.37,14.6552,321,319,2,0.006231,3,-0.999945,-2.472241,-0.887933,-1.357091,0.000000,-1.271865,-1.467589,-1.660474,-0.878468,-1.415886,-1.475696,-1.907184,-1.373377,-2.277316,0.0,0.0,-0.940905,-0.634450,42.8150,8060.480000,1175.215000,345.5,2.25,-28.70,124.57,31.0
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,5.69,138.18,2211.92,8306.69,41.66,129.62,2387.97,8066.62,329,2212,100.00,10.48,6.4213,321,318,3,0.009346,0,0.000000,-1.136900,-1.431503,-0.824992,0.999968,-1.684421,-0.722404,-0.356625,-1.126490,-1.311260,-1.260152,-0.463529,-1.434164,-0.929334,0.0,0.0,-1.204026,0.681673,42.4300,8062.526667,1155.826667,340.0,-2.28,20.49,-120.45,-32.0
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,5.70,137.98,2211.88,8312.35,41.68,129.80,2388.02,8076.05,328,2212,100.00,10.54,6.4176,321,317,4,0.012461,0,0.000000,-1.675295,-1.716508,-0.716338,0.999968,-0.750182,-0.915481,-0.524095,-0.821045,-1.241757,-1.071823,-0.269671,-0.872713,-1.531308,0.0,0.0,-0.698302,0.629779,42.2425,8065.907500,1146.377500,337.0,0.02,9.43,0.98,-1.0
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,9.00,174.82,1915.22,7994.94,36.48,164.11,2028.08,7865.80,305,1915,84.93,14.03,8.6754,321,316,5,0.015576,2,-0.999945,-1.654742,-0.935484,-1.763136,0.999945,-1.500262,-0.908397,-0.910789,-1.440557,-0.861269,-0.800727,-1.031613,-1.035006,-1.271973,0.0,0.0,-2.185794,1.153795,41.0900,8025.886000,1123.820000,330.6,-5.20,-210.25,-84.44,-23.0

In [4]:
TOP_SENSORS = [
    "sensor_11",
    "sensor_14",
    "sensor_4",
    "sensor_17",
    "sensor_9"
]

TOP_SENSORS

['sensor_11', 'sensor_14', 'sensor_4', 'sensor_17', 'sensor_9']

In [5]:
for sensor in TOP_SENSORS:

    train_df[f"{sensor}_rolling_std"] = (
        train_df.groupby("unit_number")[sensor]
        .transform(
            lambda x: x.rolling(
                window=10,
                min_periods=1
            ).std()
        )
    )

print("Rolling Std Features Added")

Rolling Std Features Added

In [6]:
for sensor in TOP_SENSORS:

    train_df[f"{sensor}_rolling_min"] = (
        train_df.groupby("unit_number")[sensor]
        .transform(
            lambda x: x.rolling(
                window=10,
                min_periods=1
            ).min()
        )
    )

print("Rolling Min Features Added")

Rolling Min Features Added

In [7]:
for sensor in TOP_SENSORS:

    train_df[f"{sensor}_rolling_max"] = (
        train_df.groupby("unit_number")[sensor]
        .transform(
            lambda x: x.rolling(
                window=10,
                min_periods=1
            ).max()
        )
    )

print("Rolling Max Features Added")

Rolling Max Features Added

In [8]:
for sensor in TOP_SENSORS:

    first_diff = (
        train_df.groupby("unit_number")[sensor]
        .diff()
    )

    second_diff = (
        first_diff.groupby(
            train_df["unit_number"]
        ).diff()
    )

    train_df[
        f"{sensor}_acceleration"
    ] = second_diff

print("Acceleration Features Added")

Acceleration Features Added

In [9]:
train_df.fillna(
    0,
    inplace=True
)

print(
    train_df.isnull().sum().sum()
)

0

In [10]:
print(train_df.shape)

(61249, 74)

In [11]:
train_df.columns.tolist()[-25:]

['sensor_17_rolling_mean',
 'sensor_11_delta',
 'sensor_14_delta',
 'sensor_4_delta',
 'sensor_17_delta',
 'sensor_11_rolling_std',
 'sensor_14_rolling_std',
 'sensor_4_rolling_std',
 'sensor_17_rolling_std',
 'sensor_9_rolling_std',
 'sensor_11_rolling_min',
 'sensor_14_rolling_min',
 'sensor_4_rolling_min',
 'sensor_17_rolling_min',
 'sensor_9_rolling_min',
 'sensor_11_rolling_max',
 'sensor_14_rolling_max',
 'sensor_4_rolling_max',
 'sensor_17_rolling_max',
 'sensor_9_rolling_max',
 'sensor_11_acceleration',
 'sensor_14_acceleration',
 'sensor_4_acceleration',
 'sensor_17_acceleration',
 'sensor_9_acceleration']

In [12]:
new_features = [
    col
    for col in train_df.columns
    if (
        "rolling" in col
        or "acceleration" in col
    )
]

corrs = (
    train_df[new_features + ["RUL"]]
    .corr()["RUL"]
    .abs()
    .sort_values(
        ascending=False
    )
)

corrs.head(20)

RUL                       1.000000
sensor_14_rolling_max     0.366867
sensor_11_rolling_max     0.232191
sensor_4_rolling_max      0.170431
sensor_14_rolling_mean    0.155744
sensor_17_rolling_max     0.140474
sensor_11_rolling_mean    0.120679
sensor_9_rolling_max      0.118139
sensor_4_rolling_mean     0.099464
sensor_4_rolling_min      0.078654
sensor_17_rolling_mean    0.072239
sensor_4_rolling_std      0.062543
sensor_17_rolling_std     0.057822
sensor_9_rolling_std      0.053008
sensor_11_rolling_std     0.052877
sensor_14_rolling_std     0.040719
sensor_14_rolling_min     0.034756
sensor_11_rolling_min     0.034547
sensor_17_rolling_min     0.029283
sensor_9_rolling_min      0.007998
Name: RUL, dtype: float64

In [13]:
train_df.to_csv(
    "../data/processed/train_advanced_features.csv",
    index=False
)

print(
    "Advanced Features Saved Successfully"
)

Advanced Features Saved Successfully

In [14]:
print(train_df.shape)

train_df.head()

(61249, 74)

,unit_number,time_cycle,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_11,sensor_12,sensor_13,sensor_14,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,max_cycle,RUL,engine_age,life_fraction,operating_cluster,sensor_1_norm,sensor_2_norm,sensor_3_norm,sensor_4_norm,sensor_5_norm,sensor_6_norm,sensor_7_norm,sensor_8_norm,sensor_9_norm,sensor_11_norm,sensor_12_norm,sensor_13_norm,sensor_14_norm,sensor_17_norm,sensor_18_norm,sensor_19_norm,sensor_20_norm,sensor_21_norm,sensor_11_rolling_mean,sensor_14_rolling_mean,sensor_4_rolling_mean,sensor_17_rolling_mean,sensor_11_delta,sensor_14_delta,sensor_4_delta,sensor_17_delta,sensor_11_rolling_std,sensor_14_rolling_std,sensor_4_rolling_std,sensor_17_rolling_std,sensor_9_rolling_std,sensor_11_rolling_min,sensor_14_rolling_min,sensor_4_rolling_min,sensor_17_rolling_min,sensor_9_rolling_min,sensor_11_rolling_max,sensor_14_rolling_max,sensor_4_rolling_max,sensor_17_rolling_max,sensor_9_rolling_max,sensor_11_acceleration,sensor_14_acceleration,sensor_4_acceleration,sensor_17_acceleration,sensor_9_acceleration
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,5.70,137.36,2211.86,8311.32,41.69,129.78,2387.99,8074.83,330,2212,100.00,10.62,6.3670,321,320,1,0.003115,0,0.000000,0.435212,-1.384507,-1.281784,0.999968,-0.750182,-1.514018,-0.607831,-0.876629,-1.207006,-1.092748,-0.385986,-0.945350,-0.327361,0.0,0.0,-0.024002,-0.079912,41.6900,8074.830000,1112.930000,330.0,0.00,0.00,0.00,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,41.69,8074.83,1112.93,330.0,8311.32,41.69,8074.83,1112.93,330.0,8311.32,0.00,0.00,0.00,0.0,0.00
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,13.61,332.10,2323.66,8713.60,43.94,312.59,2387.73,8046.13,361,2324,100.00,24.37,14.6552,321,319,2,0.006231,3,-0.999945,-2.472241,-0.887933,-1.357091,0.000000,-1.271865,-1.467589,-1.660474,-0.878468,-1.415886,-1.475696,-1.907184,-1.373377,-2.277316,0.0,0.0,-0.940905,-0.634450,42.8150,8060.480000,1175.215000,345.5,2.25,-28.70,124.57,31.0,1.590990,20.293965,88.084292,21.920310,284.454916,41.69,8046.13,1112.93,330.0,8311.32,43.94,8074.83,1237.50,361.0,8713.60,0.00,0.00,0.00,0.0,0.00
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,5.69,138.18,2211.92,8306.69,41.66,129.62,2387.97,8066.62,329,2212,100.00,10.48,6.4213,321,318,3,0.009346,0,0.000000,-1.136900,-1.431503,-0.824992,0.999968,-1.684421,-0.722404,-0.356625,-1.126490,-1.311260,-1.260152,-0.463529,-1.434164,-0.929334,0.0,0.0,-1.204026,0.681673,42.4300,8062.526667,1155.826667,340.0,-2.28,20.49,-120.45,-32.0,1.307784,14.781375,70.761173,18.193405,233.604503,41.66,8046.13,1112.93,329.0,8306.69,43.94,8074.83,1237.50,361.0,8713.60,-4.53,49.19,-245.02,-63.0,-809.19
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,5.70,137.98,2211.88,8312.35,41.68,129.80,2388.02,8076.05,328,2212,100.00,10.54,6.4176,321,317,4,0.012461,0,0.000000,-1.675295,-1.716508,-0.716338,0.999968,-0.750182,-0.915481,-0.524095,-0.821045,-1.241757,-1.071823,-0.269671,-0.872713,-1.531308,0.0,0.0,-0.698302,0.629779,42.2425,8065.907500,1146.377500,337.0,0.02,9.43,0.98,-1.0,1.131735,13.833998,60.788508,16.020820,201.755017,41.66,8046.13,1112.93,328.0,8306.69,43.94,8076.05,1237.50,361.0,8713.60,2.30,-11.06,121.43,31.0,412.57
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,9.00,174.82,1915.22,7994.94,36.48,164.11,2028.08,7865.80,305,1915,84.93,14.03,8.6754,321,316,5,0.015576,2,-0.999945,-1.654742,-0.935484,-1.763136,0.999945,-1.500262,-0.908397,-0.910789,-1.440557,-0.861269,-0.800727,-1.031613,-1.035006,-1.271973,0.0,0.0,-2.185794,1.153795,41.0900,8025.886000,1123.820000,330.6,-5.20,-210.25,-84.44,-23.0,2.757154,90.289185,72.908409,19.932386,255.241720,36.48,7865.80,1033.59,305.0,7994.94,43.94,8076.05,1237.50,361.0,8713.60,-5.22,-219.68,-85.42,-22.0,-323.07

In [15]:
train_df.shape

(61249, 74)

In [16]:
train_df.columns.tolist()[-30:]

['sensor_20_norm',
 'sensor_21_norm',
 'sensor_11_rolling_mean',
 'sensor_14_rolling_mean',
 'sensor_4_rolling_mean',
 'sensor_17_rolling_mean',
 'sensor_11_delta',
 'sensor_14_delta',
 'sensor_4_delta',
 'sensor_17_delta',
 'sensor_11_rolling_std',
 'sensor_14_rolling_std',
 'sensor_4_rolling_std',
 'sensor_17_rolling_std',
 'sensor_9_rolling_std',
 'sensor_11_rolling_min',
 'sensor_14_rolling_min',
 'sensor_4_rolling_min',
 'sensor_17_rolling_min',
 'sensor_9_rolling_min',
 'sensor_11_rolling_max',
 'sensor_14_rolling_max',
 'sensor_4_rolling_max',
 'sensor_17_rolling_max',
 'sensor_9_rolling_max',
 'sensor_11_acceleration',
 'sensor_14_acceleration',
 'sensor_4_acceleration',
 'sensor_17_acceleration',
 'sensor_9_acceleration']